name: dr_kevell
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # state management and dependency injections

  dartz: ^0.10.1
  dio: ^5.4.0
  get_it: ^7.6.0
  injectable: ^2.1.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.3
  mqtt_client: ^10.0.0
  flutter_svg: ^2.0.7
  syncfusion_flutter_datepicker: ^22.2.9


  lottie: ^2.4.0
  internet_connection_checker_plus: ^1.0.1
  flutter_secure_storage: ^8.0.0
  syncfusion_flutter_charts: ^22.2.9
  sliver_tools: ^0.2.12
  pdf: ^3.10.4
  path_provider: ^2.1.1
  share: ^2.0.4
  image_cropper: ^4.0.1
  image_picker: ^1.0.2
  permission_handler: ^10.4.3
  webview_flutter: ^4.2.3
# video call
  socket_io_client: ^2.0.3+1
  flutter_webrtc: ^0.9.45
  firebase_core: ^2.23.0
  firebase_messaging: ^14.6.8
  # sqflite: ^2.3.0 
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  audioplayers: ^5.2.0
  audio_waveforms: ^1.0.4
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  open_file: ^3.3.2
  # flutter_pdfview: ^1.3.2
  
  # just_audio: ^0.9.10
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.4.6
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  injectable_generator: ^2.1.5
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.3.1

  flutter_launcher_icons: ^0.13.1
  isar_generator: ^3.1.0+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  branding: assets/images/branding.png
  color_dark: "#121212"
  image_dark: assets/images/logo.png
  branding_dark: assets/images/branding.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#121212"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/othor/
    - assets/icons/profile/
    - assets/icons/bottom_navigtion/
    - assets/lottie/
